### ISSUE TITLE
Wrong country flag & region doesn't appear

### ISSUE THREAD

**Issue by St3rMi88** [CS2Browser/cs2-server-browser#18]
Hello,
our servers are marked with the American flag, but them are hosted on a German server. Is it possible to fix?
Furthermore, the "region" data doesn't appear, do we need to add some data to the servers cfg?

Thanks in advance.

![image](https://github.com/CS2Browser/cs2-server-browser/assets/151388808/02b42fb9-1e80-4b3c-94fb-5895d0653587)

**Comment by JMorell** [comment]
Check now

**Comment by St3rMi88** [comment]
> Check now

It looks fine now! Thanks :)
