### ISSUE TITLE
Server shows wrong country flag.

### ISSUE THREAD

**Issue by DEPSTRCZ** [CS2Browser/cs2-server-browser#22]
Hello, we have our server listed on the site. Our server is in Germany. However, the server list shows it as France. Which is wrong. I didn't find any contact/support so I am writing here. We primarily focus on community-based on completely different countries and we would like to change the flag. Is it possible?

**Comment by JMorell** [comment]
yes, there is a pending addition so that you can modify it yourself, but for the moment, you should tell me which servers are affected and I will change it myself.

**Comment by DEPSTRCZ** [comment]
Thanks for the response. It is [this one](https://cs2browser.com/gameserver/43023/cz-sk-eu-gamenest-cz-only-mirage-vip-ws-knife-/) the server is in germany. But if possible can you set it to Czech republic flag? Thanks

**Comment by JMorell** [comment]
Fixed!

**Comment by alnoisegit** [comment]
Hey I didn't want to open a new issue with the same problem. Is there any chance you could fix [my server](https://cs2browser.com/gameserver/145717/surf-n-chill-easy-us-/) with the same issue? It's showing up as an EU server while it's hosted in the US.

**Comment by JMorell** [comment]
> Hey I didn't want to open a new issue with the same problem. Is there any chance you could fix [my server](https://cs2browser.com/gameserver/145717/surf-n-chill-easy-us-/) with the same issue? It's showing up as an EU server while it's hosted in the US.

Changed

**Comment by boomix** [comment]
Hey! How is the progress with this feature, to change country? I have same thing, https://cs2browser.com/gameserver/134147/lv-identy-lv-public-ws-knife-skins/ , it is hosted in Sweden, but needs to show up as Latvian server.

**Comment by JMorell** [comment]
> Hey! How is the progress with this feature, to change country? I have same thing, https://cs2browser.com/gameserver/134147/lv-identy-lv-public-ws-knife-skins/ , it is hosted in Sweden, but needs to show up as Latvian server.

Changed!
