### ISSUE TITLE
Server banner request

### ISSUE THREAD

**Issue by brkvlr** [CS2Browser/cs2-server-browser#24]
Can server banners like Gametracker be added?

**Comment by JMorell** [comment]
those that are used to share the server on forums and other websites? could be

**Comment by JMorell** [comment]
those that are used to share the server on forums and other websites? could be

**Comment by brkvlr** [comment]
@JMorell 45.10.56.191:27015 there is a problem with my IP address being listed

**Comment by JMorell** [comment]
This is the server: https://cs2browser.com/gameserver/26067/tr-runaway-cs2-zombie-escape-discord-gg-runaway/#

If the server receives no players in the last 24 hours, it disappears from the server list until someone comes in to play for a few minutes.

**Comment by brkvlr** [comment]
Our server has been open for days and is still not listed. We are playing with 15 people.
ip: 45.10.56.191:27015 
@JMorell

**Comment by JMorell** [comment]
It seems that the server is configured as “secure”: false.

**Comment by brkvlr** [comment]
Thanks for information.
