### ISSUE TITLE
Broken ping filters with Oceanic servers

### ISSUE THREAD

**Issue by ghost** [CS2Browser/cs2-server-browser#28]
All oceanic game servers with ping filters on are not showing, even though I get 10 ping in game.
![image](https://github.com/CS2Browser/cs2-server-browser/assets/165794608/140a6cc4-0ae0-4aa3-a3ae-be0ed7c40635)

**Comment by JMorell** [comment]
Are you from oceania?

**Comment by ghost** [comment]
> Are you from oceania?

Yes

**Comment by JMorell** [comment]
I've made a change so that when you select a region, it ignores the ping filter.
