### ISSUE TITLE
Help How to add my server

### ISSUE THREAD

**Issue by Carloscb22** [CS2Browser/cs2-server-browser#30]
How do I add my server? Not listed

**Comment by JMorell** [comment]
the servers are added automatically, please tell me the IP address.

**Comment by NaathySz** [comment]
> the servers are added automatically, please tell me the IP address.

couldn't find mine either. Changed the host 3 times in a week and the first host was showing in list. Maybe got blacklisted for some reason?

btw this is new ip `169.150.198.105:26645`

**Comment by JMorell** [comment]
> > the servers are added automatically, please tell me the IP address.
> 
> couldn't find mine either. Changed the host 3 times in a week and the first host was showing in list. Maybe got blacklisted for some reason?
> 
> btw this is new ip `169.150.198.105:26645`

Server whitelisted, will appear in a few minutes.
