### ISSUE TITLE
GeoIP update

### ISSUE THREAD

**Issue by toorisrael** [CS2Browser/cs2-server-browser#32]
Hi, could you please update geoip database you're using?
Some of my servers have wrong location, which we've already corrected in ip2location/maxmind.

**Comment by JMorell** [comment]
yes, but you'll have to give me the list of servers and the region they go to.

**Comment by toorisrael** [comment]
I mean just geoip db update, but if you need specific addresses to correct:
193.70.126.131
193.70.126.132
Located in Poland.

**Comment by JMorell** [comment]
I then correct it, but the servers that already have a region assigned must be updated manually

**Comment by JMorell** [comment]
Fixed.
