### ISSUE TITLE
This gameserver is not online for one of the following reasons

### ISSUE THREAD

**Issue by j1ton** [CS2Browser/cs2-server-browser#38]
Greetings. For some reason, my server shows an error:

This game server is not online for one of the following reasons:
The server has had no players in the last 24 hours
IP address changed
Is under DDOS attack

The server is fully operational, there were no DDOS attacks, there is online, what is the problem?

**Comment by JMorell** [comment]
Hello, IP and port?

**Comment by j1ton** [comment]
hello, 37.230.162.14:27015

**Comment by JMorell** [comment]
If the server is more than 24 hours without any player, it will appear with this warning, I don't see it in the banned list.

**Comment by j1ton** [comment]
> If the server is more than 24 hours without any player, it will appear with this warning, I don't see it in the banned list.

At the moment there are 4 people on the online server, but your site does not show that there is online. So what's the problem? There is no server in the browser search, the server cannot be empty for 24 hours, players log on to it.

**Comment by JMorell** [comment]
okay, I'll check it this afternoon.

**Comment by JMorell** [comment]
I have seen the problem, the server is listed as ‘secure’: false

**Comment by j1ton** [comment]
here are the screenshots, there are 0 visits in 24 hours.
What should I do?
https://imgur.com/a/q99AelM

**Comment by j1ton** [comment]
Here is a screenshot from the last 30 days.
It can be seen here that the last date is May 29th, there is nothing further.
https://imgur.com/a/bQWiG6b

**Comment by JMorell** [comment]
![image](https://github.com/CS2Browser/cs2-server-browser/assets/6134888/889d6962-9215-48ca-85d2-c08a4d2a2596)
This is false.

**Comment by j1ton** [comment]
understood, turned it on, thanks!
