### ISSUE TITLE
Server not showing

### ISSUE THREAD

**Issue by NordicGamerFE** [CS2Browser/cs2-server-browser#39]
Is there a reason my server is not showing
65.109.62.26:25568

**Comment by JMorell** [comment]
Have you had players in the last 24 hours?

**Comment by NordicGamerFE** [comment]
yeah i've been on it myself loads during the past 24 hr's

**Comment by JMorell** [comment]
Last time it detected players was on this date: 2024-06-08 06:32:56

**Comment by NordicGamerFE** [comment]
I've been on it everyday for hr's

**Comment by JMorell** [comment]
I think I've seen the problem, the server hostname can't be Counter-Strike 2, as we have it filtered to not register new servers that haven't been configured yet.

**Comment by NordicGamerFE** [comment]
Ah i think i've fixed it now some plugin shat the bed that I was using for hostname

**Comment by NordicGamerFE** [comment]
![image](https://github.com/CS2Browser/cs2-server-browser/assets/18188155/d9212c3c-afee-42cd-9917-2eb584c63447)
:3
