### ISSUE TITLE
Gameserver is showing up in the wrong country.

### ISSUE THREAD

**Issue by Ssolheid03** [CS2Browser/cs2-server-browser#40]
I have double checked all of my settings. Server is located in Boston, MA. On this website server is listing as in europe.

![Screenshot_20240619_111129_Chrome](https://github.com/CS2Browser/cs2-server-browser/assets/173288613/c969327b-2894-4634-b4c5-e8cdc770b5b4)

**Comment by JMorell** [comment]
Fixed!

**Comment by Ssolheid03** [comment]
thank you kind sir!
