### ISSUE TITLE
"gameserver is not online..."

### ISSUE THREAD

**Issue by y3request** [CS2Browser/cs2-server-browser#41]
https://cs2browser.com/gameserver/126908/ffa-dm-fy_maps-showdmg-reload-heal/

The server is online and secure. It used to work, dunno why it says it is offline now.
shows up in steam server list, and my favorites fine. Not on cs2browser website tho

**Comment by JMorell** [comment]
have had players in the last 24 hours?

**Comment by JMorell** [comment]
I see players on the server, I close the ticket.
