### ISSUE TITLE
Dont show  server ip here  if server running without GSLT

### ISSUE THREAD

**Issue by rpkaul** [CS2Browser/cs2-server-browser#45]
I am explaining my situation. Basically, I run tournaments in my country and I don't use GSLT to avoid IP leaks in the server browser. However, my server is still visible on https://cs2browser.com/ and ddoser copy ip from this site and my servers are getting heavy DDoS attacks during my tournament matches or Is there any command to hide or avoid server listing here?

**Comment by JMorell** [comment]
Hello, we can look at it without any problem, if you want we can talk about it privately so that information is not diffused. But you could look at adding a hostname filter, so that those servers could not be tracked.

**Comment by rpkaul** [comment]
@JMorell please share your discord so i can add my discord  -  lotkancha
also i changed my host name as well but  with country filter my server is showing on top and again same issue

**Comment by JMorell** [comment]
Should already appear hidden, if you have any more problems in the future, let me know and we will check it again without any problem.

**Comment by shaikhnedab** [comment]
please if possible, give us option to hide servers from listing.

**Comment by JMorell** [comment]
I will consider it but first I should think of a way to prove that the server in question is yours.

**Comment by thed4ddy** [comment]
Server ownership could be proven by adding a unique tag, should be only possible for server owners to do so.

Edit: Could be a temporary step for confirming server ownership, which could be removed later on or so.

**Comment by shaikhnedab** [comment]
> Server ownership could be proven by adding a unique tag, should be only possible for server owners to do so.

yep just like gametracker

**Comment by JMorell** [comment]
> Server ownership could be proven by adding a unique tag, should be only possible for server owners to do so.
> 
> Edit: Could be a temporary step for confirming server ownership, which could be removed later on or so.

That's a possibility, but I think it's only possible with the hostname of the server and that seems a bit ugly to me.
