### ISSUE TITLE
Able to change server country

### ISSUE THREAD

**Issue by ghostt187** [CS2Browser/cs2-server-browser#53]
Would be good feature if could add to claim server like gametracker and change server country the reason for this is that for example i use server ip germany but all my players are from albania and if they open the website to search for servers in albania my server own show... dk if this is possible but if it is would be good

**Comment by JMorell** [comment]
It is planned to be done in the near future.

**Comment by rptr188** [comment]
Do any technical obstacles exist for this to implement, as I see this issue was opened 3 months ago? Can we request manual change for an IP if you don't only rely on a GeoIP DB?

**Comment by JMorell** [comment]
Hi, the technical problem is finding the most comfortable methodology to verify the owner of the server. If you give me the IPs I can change it manually.

**Comment by rptr188** [comment]
> Hi, the technical problem is finding the most comfortable methodology to verify the owner of the server. If you give me the IPs I can change it manually.

Maybe I'd suggest to do similar as GameTracker does -> GameTrackerClaimServer in hostname but to do variation with some unique ID in the servername to verify the ownership... If an owner is smart, he'll not give RCON flag to admins... As far as I can see it removes server from the page after some time of inactivity? So there's no much room for manipulating

Regarding IPs
217.156.22.174:27015 -> from RO to Serbia
217.156.22.174:27016 -> from RO to Serbia

Thanks

**Comment by JMorell** [comment]
> > Hi, the technical problem is finding the most comfortable methodology to verify the owner of the server. If you give me the IPs I can change it manually.
> 
> Maybe I'd suggest to do similar as GameTracker does -> GameTrackerClaimServer in hostname but to do variation with some unique ID in the servername to verify the ownership... If an owner is smart, he'll not give RCON flag to admins... As far as I can see it removes server from the page after some time of inactivity? So there's no much room for manipulating
> 
> Regarding IPs 217.156.22.174:27015 -> from RO to Serbia 217.156.22.174:27016 -> from RO to Serbia
> 
> Thanks

Changed.

**Comment by rptr188** [comment]
> > > Hi, the technical problem is finding the most comfortable methodology to verify the owner of the server. If you give me the IPs I can change it manually.
> > 
> > 
> > Maybe I'd suggest to do similar as GameTracker does -> GameTrackerClaimServer in hostname but to do variation with some unique ID in the servername to verify the ownership... If an owner is smart, he'll not give RCON flag to admins... As far as I can see it removes server from the page after some time of inactivity? So there's no much room for manipulating
> > Regarding IPs 217.156.22.174:27015 -> from RO to Serbia 217.156.22.174:27016 -> from RO to Serbia
> > Thanks
> 
> Changed.

We have changed IPs (please leave the old one if possible for some time), can you please edit these IPs:
213.181.206.240:27015 > Serbia
213.186.206.240:27016 > Serbia

Both currently on Hungary...

Thanks in advance

**Comment by JMorell** [comment]
> > > > Hi, the technical problem is finding the most comfortable methodology to verify the owner of the server. If you give me the IPs I can change it manually.
> > > 
> > > 
> > > Maybe I'd suggest to do similar as GameTracker does -> GameTrackerClaimServer in hostname but to do variation with some unique ID in the servername to verify the ownership... If an owner is smart, he'll not give RCON flag to admins... As far as I can see it removes server from the page after some time of inactivity? So there's no much room for manipulating
> > > Regarding IPs 217.156.22.174:27015 -> from RO to Serbia 217.156.22.174:27016 -> from RO to Serbia
> > > Thanks
> > 
> > 
> > Changed.
> 
> We have changed IPs (please leave the old one if possible for some time), can you please edit these IPs: 213.181.206.240:27015 > Serbia 213.186.206.240:27016 > Serbia
> 
> Both currently on Hungary...
> 
> Thanks in advance

Done!

**Comment by ghostt187** [comment]
sorry but has this feature been added since it has been closed @JMorell
