### ISSUE TITLE
How to add an server?

### ISSUE THREAD

**Issue by illusion035** [CS2Browser/cs2-server-browser#56]
Hello, how to add my CS2 server in **cs2browser.com** ?

IP Address is **45.144.155.110:27015**

API is working - https://api.steampowered.com/IGameServersService/GetServerList/v1/?key=apikeyhere&filter=%5Caddr%5C45.144.155.110:27015

Edit: I find it, sorry - https://cs2browser.com/gameserver/171127/cs2-bg-net-public-skins-endroundsounds-newmaps-rtv-f/

**Comment by JMorell** [comment]
Hi, it is added automatically but only if there are players inside for a few minutes.
