### ISSUE TITLE
Disconnected upon attempting join

### ISSUE THREAD

**Issue by Fuzzy2426** [CS2Browser/cs2-server-browser#57]
I have set up everything that I know of correctly, but when I click on a server and it says "Open Steam", it seems like CS2 starts to load something, before quickly giving a "Disconnected" prompt. Am I doing something wrong, is it bugged, etc?

**Comment by Fuzzy2426** [comment]
It also does this when I try to directly connect to a server by using the IP address in the console.

**Comment by JMorell** [comment]
In one of the latest game updates, they broke the connection error messages when logging in and now you always get the message ‘Disconnected’, possibly you are trying to log in to a server that is full or something like that.
