### ISSUE TITLE
Cut linked list overflow (exhausted memory allocator)

### ISSUE THREAD

**Issue by FazeX4091** [CS2Browser/cs2-server-browser#59]
Hello. Everytime i try to connect to a server, the following issue keep showing and game crashes.
Cut linked list overflow (exhausted memory allocator)

**Comment by FazeX4091** [comment]
> Hello. Everytime i try to connect to a server, the following issue keep showing and game crashes. Cut linked list overflow (exhausted memory allocator)

I have tried to reinstall cs2 but it didnt change anything

**Comment by JMorell** [comment]
It's not a browser-related error, but do you have updated drivers?

**Comment by FazeX4091** [comment]
Yes. I have updated all my drivers. 
This has never happened before, it seems like it started after the latest cs2 update.
I know that im not the only one with this problem.

**Comment by JMorell** [comment]
Some people say that you have to try to connect several times until it lets you access.

**Comment by sylviejunkie** [comment]
i'm having the same issue, and connecting multiple times doesn't seem to help, i've done it like 8 times already and nothing. on certain servers/maps i can join, but others will just give that error and crash every time.

**Comment by JMorell** [comment]
It's a very common error, it's a bug in the game, you have to try to enter several times until it lets you in.
