### ISSUE TITLE
GeoIP Refresh Question

### ISSUE THREAD

**Issue by jithatsonei** [CS2Browser/cs2-server-browser#60]
Hello!

I am curious how often the GeoIP DB is refreshed, a couple months back we recently took possession of an IP block that showed in EU in some databases which I have gotten corrected, but still haven't seen them updated on the site

Thanks!

**Comment by JMorell** [comment]
the refresh is now not done automatically, I have to implement it.

**Comment by jithatsonei** [comment]
> the refresh is now not done automatically, I have to implement it.

sounds good, if you manual update soon i be forever grateful, even better if you implement auto updates - nonetheless thanks for the response and I will close this out

EDIT: if you want to fix now its 66.118.246.0/24: NL -> US :3
