### ISSUE TITLE
Ban this garbage please

### ISSUE THREAD

**Issue by imusicandme** [CS2Browser/cs2-server-browser#61]
Yo, when i'm trying to find server on NA that's what i see, all servers fake
![image](https://github.com/user-attachments/assets/9f69ff74-2b91-4969-bd62-ca4d2200dc9e)

**Comment by JMorell** [comment]
Thank you for report it, they will be gone in 24 hours.

**Comment by imusicandme** [comment]
> Thank you for report it, they will be gone in 24 hours.

Thanks boss
