### ISSUE TITLE
server no longer showing

### ISSUE THREAD

**Issue by sygobit** [CS2Browser/cs2-server-browser#62]
One of my servers 139.99.135.153:27019 is no longer showing in the browser. It briefly showed for a few days but hasn't been displayed for a while now. 
1. GSLT is present
2. API shows the server
3. a server with similar config running on :27015 shows.
4. both servers are secure and sv_pure 1
5. I have repeatedly sat on the server for hours at a time waiting for it to sync, with no results.

**Comment by JMorell** [comment]
Hi, try removing the word Test from the hostname.

**Comment by sygobit** [comment]
Thanks, this is working now. Although interesting to note I could see some other servers showing up with test in their names... 

Maybe it could be worth documenting these situations where servers are hidden? It would make it easier to quickly check what I can do before raising an issue, saves you time responding to these tickets too!

**Comment by JMorell** [comment]
I'll make a note to keep it in mind.
