### ISSUE TITLE
Outdated game information

### ISSUE THREAD

**Issue by dvlopjs** [CS2Browser/cs2-server-browser#65]
When I look at the time of the players who are on the server, it increases progressively but when it refreshes the time goes back, I think it has something to do with the caching of the information

10:01 PM
- ![image](https://github.com/user-attachments/assets/7f21dc4a-2c88-44cb-a99b-734637469d01)
- ![image](https://github.com/user-attachments/assets/1b83e158-4bd3-44ab-879b-c774c2c8dfce)

10:02 PM
- ![image](https://github.com/user-attachments/assets/819a179e-37c3-43b7-9dd5-68f61e8dd595)
- ![image](https://github.com/user-attachments/assets/0d191264-690f-4d7c-ae55-5fb3ce12879e)

**Comment by JMorell** [comment]
The player list is fetched every X seconds, so if you refresh the list before the next refresh, that time will appear reset.
