### ISSUE TITLE
Change server country

### ISSUE THREAD

**Issue by Dudnes** [CS2Browser/cs2-server-browser#69]
Hi,

My CS2 servers are in Poland and some of them are displayed as France, 
can I ask to change all of them to PL?

https://cs2browser.com/gameserver/105567/katujemy-eu-losowe-super-moce-skins/
https://cs2browser.com/gameserver/21799/katujemy-eu-mirage-skins-knife-rank-vi/
https://cs2browser.com/gameserver/21800/katujemy-eu-mirage-2-skins-knife-g/
https://cs2browser.com/gameserver/122079/katujemy-eu-arena-1v1-skins-knife-g/

**Comment by JMorell** [comment]
Fixed!
