### ISSUE TITLE
Multiple IPs for the same server

### ISSUE THREAD

**Issue by Mikasan15** [CS2Browser/cs2-server-browser#71]
Hello, can you please make all those pages point to the same server since it's the same just the name and IP have changed.

Dead servers :
https://cs2browser.com/gameserver/128740/dz-hell-zone-x-ggez-public-server-knife-ws-rank/
https://cs2browser.com/gameserver/174203/dz-hell-zone-public-server-agents-knife-ws-rank-vip/
https://cs2browser.com/gameserver/201367/dz-hell-zone-public-server-agents-knife-ws-rank-vip/
https://cs2browser.com/gameserver/213069/dz-hell-zone-dev-server/
https://cs2browser.com/gameserver/167568/dz-hell-zone-cs2-public-server-skins-free-vip/
https://cs2browser.com/gameserver/468/dz-hell-zone-public-server-knife-ws-rank/

Real running server:
https://cs2browser.com/gameserver/219860/dz-hell-zone-fun-awp-only-powered-by-qonzer-com-ws/

Also the country is showing "Iran" can you please set it to Algeria (DZ) ?

Thank you for your help ♥

**Comment by JMorell** [comment]
I can't do what you say about being redirected to the other ip but think that those old servers will no longer appear in the list, they are only accessible if you have the URL.

I have changed the server region.
