### ISSUE TITLE
Servers show populated when they are empty

### ISSUE THREAD

**Issue by koewi88** [CS2Browser/cs2-server-browser#9]
I had it a few times, that i wanted to play on a Server, that was shown as populated, but was empty after joining.

Example right now:
Looking for german servers with aim maps at 2:30am. This server shows up:
https://cs2browser.com/gameserver/21720/refrag-gg-aimmap-dm-eu-3/
169.150.247.198:26770

It shows that it has 9 players ... when i join its empty.

Same for this one:
https://cs2browser.com/gameserver/36923/cs2-aimdm-3-de-cybershoke-net/
168.119.196.20:27032

It shows 4 people ... its empty, if i join it restarts with bots.

Or this one:
https://cs2browser.com/gameserver/2422/ger-cs2-ballerwiese-3xl-d2-only-16k-/
45.138.49.230:27015

Shows 20 players ... its empty.

**Comment by JMorell** [comment]
We are about to incorporate a server reporting system to clean up all of this, thank you very much for reporting it.

**Comment by JMorell** [comment]
We are about to incorporate a server reporting system to clean up all of this, thank you very much for reporting it.
